// Generated by Copilot
declare module 'glob' {
    export function glob(pattern: string, options?: any): Promise<string[]>;
    export function globSync(pattern: string, options?: any): string[];
    export namespace glob {
        const sync: typeof globSync;
    }
}
