// Generated by Copilot
import * as sinon from 'sinon';
import * as vscode from 'vscode';

// Setup function to initialize test environment
export async function setupTestEnvironment() {
    // Activate the extension before running tests
    const extension = vscode.extensions.getExtension('timheuer.jsondbg');

    if (extension && !extension.isActive) {
        await extension.activate();
    }

    return {
        extension,
        dispose: () => {
            // Clean up any test resources here
        }
    };
}

// Define a proper type for debug variables since VSCode doesn't export this type
interface DebugVariableLike {
    name: string;
    value: string;
    variablesReference: number;
    [key: string]: any;
}

// Create a mock debug variable for testing
export function createMockVariable(props: Partial<DebugVariableLike> = {}): DebugVariableLike {
    return {
        name: 'testVar',
        value: '{"test": "value"}',
        variablesReference: 1,
        ...props
    };
}
