// Generated by Copilot

// Add missing type definitions for VSCode debugger
declare module 'vscode' {
    // Extend the vscode namespace with debug types that might be missing
    export namespace debug {
        interface DebugVariable {
            name: string;
            value: string;
            variablesReference: number;
            evaluateName?: string;
            presentationHint?: object;
            type?: string;
            memoryReference?: string;
            namedVariables?: number;
            indexedVariables?: number;
        }
    }
}
